name: Cart Quotation for Woocommerce Plugin Bug Report
description: Report a bug in Cart Quotation for Woocommerce
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to report a possible bug in Cart Quotation for Woocommerce!"
              
  - type: textarea
    attributes:
      label: Description
      description: >-
        Please write a brief description of the bug, including what you expected and what actually happened.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: >-
        Please list all the steps needed to reproduce the bug in an *isolated* way (e.g. a clonable GitHub repository, or a Cart Quotation for Woocommerce snippet that works on a clean environment).
      placeholder: >-
        1. Go to "..."
        2. Result shows X but should be Y
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here, such as screenshots, error logs, etc.

  - type: input
    attributes:
      label: Cart Quotation for Woocommerce Version
    validations:
      required: true

  - type: input
    attributes:
      label: WordPress Version
    validations:
      required: true

  - type: input
    attributes:
      label: PHP Version
    validations:
      required: true


  - type: textarea
    attributes:
      label: Additional environment details
      description: Frontend framework, additional Cart Quotation for Woocommerce extensions (and their versions), etc.

  - type: checkboxes
    attributes:
      label: Please confirm that you have searched existing issues in the repo.
      description: >-
        You can do this by searching https://github.com/digimapleinc/cart-quotation-for-woocommerce/issues.
      options:
        - label: 'Yes'
    
