name: Feature request
description: Suggest an idea, feature, or enhancement for Cart Quotation for WooCommerce.
body:
  - type: markdown
    attributes:
      value: >-
        Thank you for taking the time to submit a feature request for Cart Quotation for WooCommerce.


        Before creating a new feature request, please make sure to search the plugin's repository for [existing feature requests](https://github.com/digimapleinc/cart-quotation-for-woocommerce/issues).
  - type: textarea
    attributes:
      label: What problem does this address?
      description: >-
        Please describe the problem you are trying to solve, including why you think this is a problem.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is your proposed solution?
      description: >-
        Please provide a clear and concise description of your suggested solution.
      placeholder: What I'd like to see happen is [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
      description: >-
        Please list any alternatives you have considered, and why you think your solution is better.
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
