name: Deploy to Github
on:
  release:
    types: [ published ]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl
          tools: composer

      - name: Install PHP dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Create Artifact
        run: |
          composer run-script zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dm-cart-quotation
          path: plugin-build/dm-cart-quotation.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: plugin-build/dm-cart-quotation.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}